### PR TITLE
Fix apostrophe in install path issue

### LINKED ISSUE #48: Cannot install extension with "'" in username/users path
Port changes from microsoft/vscode-azurearmtools#356

### PR DESCRIPTION
**Pull request by sfoslund**
Fixes #48 

cc @StephenWeatherford

### CODE REVIEW

File: vscode-dotnet-runtime-library/src/Acquisition/DotnetCoreAcquisitionWorker.ts [hunk 1]
```diff
@@ -27,7 +27,8 @@ export class DotnetCoreAcquisitionWorker {
     private acquisitionPromises: { [version: string]: Promise<string> | undefined };
 
     constructor(private readonly context: IAcquisitionWorkerContext) {
-        this.installDir = path.join(this.context.storagePath, '.dotnet');
+        const installFolderName = process.env.VSCODE_DOTNET_INSTALL_FOLDER || '.dotnet';
```
Comment (NTaylorMullen) [inline vscode-dotnet-runtime-library/src/Acquisition/DotnetCoreAcquisitionWorker.ts]: if `VSCODE_DOTNET_INSTALL_FOLDER` is meant to only be there for testing prefix it with `__`.
