### PR TITLE
delete the install folder created for apostrophe

### LINKED ISSUE #1410: Running Test Creates folder vscode-dotnet-runtime-library/test' for' apostrophe/
# Describe the bug

Running the tests added in https://github.com/dotnet/vscode-dotnet-runtime/pull/1372 adds the folder vscode-dotnet-runtime-library/test' for' apostrophe/
as well as to the runtime extension folder sometimes. I'm not sure if this change also caused this, but sometimes it will open up a win32 file when trying to run the tests. The test should clean up this folder or create it in somewhere else on disk like temp and still clean it up.

### PR DESCRIPTION
**Pull request by JL03-Yue**
fixes #1410

### CODE REVIEW

File: vscode-dotnet-runtime-library/src/Acquisition/AcquisitionInvoker.ts [hunk 1]
```diff
@@ -33,7 +33,7 @@ export class AcquisitionInvoker extends IAcquisitionInvoker {
     private noPowershellError = `powershell.exe is not discoverable on your system. Is PowerShell added to your PATH and correctly installed? Please visit: https://learn.microsoft.com/powershell/scripting/install/installing-powershell-on-windows.
 You will need to restart VS Code after these changes. If PowerShell is still not discoverable, try setting a custom existingDotnetPath following our instructions here: https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md.`
 
-    constructor(extensionState: IExtensionState, eventStream: IEventStream, timeoutTime : number) {
+    constructor(extensionState: IExtensionState, eventStream: IEventStream, timeoutTime : number, installFolder?: string) {
```
Comment (nagilson) [inline vscode-dotnet-runtime-library/src/Acquisition/AcquisitionInvoker.ts:36]:
```suggestion
    constructor(extensionState: IExtensionState, eventStream: IEventStream, timeoutTime : number) {

```

It looks like `installFolder` is never used in the true class, so I would not include it in the constructor here

**Review by nagilson — APPROVED** [review]
This LGTM, thank you for swiftly responding to remedy the issue 😄
